.PHONY: all clean

PROJECT = pades.exe

CC = gcc
CFLAGS = -std=c99 -g -I/mingw32/include/SDL
LDFLAGS = -lmingw32 -lSDLmain -lSDL -lSDL_gfx


all: $(PROJECT)

$(PROJECT): main.c
	$(CC) $(CFLAGS) -o $(PROJECT) $< $(LDFLAGS)

clean:
	rm -rf $(PROJECT)
